apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod1
  template:
    metadata:
      labels:
        app: my-pod1
    spec:
      containers:
        - name: python-container1
          image: pavan70/python:v2
          command: ["python", "-m", "http.server", "8080"]
